#!/bin/bash

if [ -x $1 ]; then
    echo "Param 1 should be a host to check"
    exit 1
fi

DAYS_TO_TEST=15
CHECK=./check
PUSHOVER=python-pushover/send-message
PUSHOVER_APP=cert-checker

days=$($CHECK --host $HOST)

re='^[0-9]+$'
if ! [[ "$days" =~ $re ]] ; then
   $PUSHOVER -a $PUSHOVER_APP -t "Cert-Checker Failed" -m "$days"
   exit 1
fi

if [ $days -lt $DAYS_TO_TEST ]; then
   $PUSHOVER -a $PUSHOVER_APP -t "Cert-Checker Failed" -m "WARNING: $HOST expires in $days days"
fi
