#!/usr/bin/python3.5

import socket
import ssl
import datetime
import argparse

## Parse cli args
parser = argparse.ArgumentParser(description='Return the number of days until an SSL cert expires')
parser.add_argument('--host', required=True, help='hostname')
args = parser.parse_args()


def ssl_expiry_datetime(hostname):
    ssl_date_fmt = r'%b %d %H:%M:%S %Y %Z'

    context = ssl.create_default_context()
    conn = context.wrap_socket(
        socket.socket(socket.AF_INET),
        server_hostname=hostname,
    )
    # 3 second timeout
    conn.settimeout(3.0)

    try:
        conn.connect((hostname, 443))
        ssl_info = conn.getpeercert()
        # parse the string from the certificate into a Python datetime object
        return datetime.datetime.strptime(ssl_info['notAfter'], ssl_date_fmt)
    except socket.gaierror:
        print("Can't find hostname ({})".format(hostname))
        raise SystemExit
    except:
        raise

now = datetime.datetime.now()
expire = ssl_expiry_datetime(args.host)
diff = expire - now
print(diff.days)
